### ISSUE TITLE
Branch naming

### ISSUE THREAD

**Issue by claireinez** [olot/olot.github.io#42]
You should name your branches according to what the code in it does. Using something like your own name is useful for your team right now, but when you look back on the commit history, you want to see exactly what was done and when.

**Comment by MyPitit** [comment]
@nofootnotes thanks a lot for the advice. Now we have a better understanding about how to use branches.

**Comment by claireinez** [comment]
Great! I'll close this issue in the faith you'll use better names next week :smile:
